-- Run this in your Supabase SQL editor after creating the project.

-- Enable UUID extension
create extension if not exists "uuid-ossp";

-- 1. PROFILES (one per authenticated user)
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- 2. SETTINGS
create table public.settings (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  show_aspirations boolean not null default false,
  show_practices boolean not null default false,
  show_reflections boolean not null default false,
  theme text not null default 'light' check (theme in ('light', 'dark'))
);

-- 3. MOTIVATIONS
create table public.motivations (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  text text not null default '',
  updated_at timestamptz not null default now()
);

-- 4. TASKS
create table public.tasks (
  id bigint not null primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  day_index int not null check (day_index between 0 and 6),
  text text not null,
  status text not null default 'pending' check (status in ('pending', 'completed')),
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_tasks_user_day on public.tasks(user_id, day_index);

-- 5. OVERDUE TASKS
create table public.overdue_tasks (
  id bigint not null primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  text text not null,
  from_day text not null,
  created_at timestamptz not null default now()
);

create index idx_overdue_tasks_user on public.overdue_tasks(user_id);

-- 6. GOALS
create table public.goals (
  id bigint not null primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  emoji text not null default '🎯',
  title text not null,
  progress int not null default 0 check (progress between 0 and 100),
  deadline text not null default '',
  notes text not null default '',
  sort_order int not null default 0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index idx_goals_user on public.goals(user_id);

-- 7. GOAL MILESTONES
create table public.goal_milestones (
  id bigint generated by default as identity primary key,
  goal_id bigint not null references public.goals(id) on delete cascade,
  text text not null,
  done boolean not null default false,
  sort_order int not null default 0
);

create index idx_goal_milestones_goal on public.goal_milestones(goal_id);

-- 8. HABITS
create table public.habits (
  id bigint not null primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  icon text not null default '🌱',
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index idx_habits_user on public.habits(user_id);

-- 9. HABIT LOGS
create table public.habit_logs (
  id bigint generated by default as identity primary key,
  habit_id bigint not null references public.habits(id) on delete cascade,
  day_index int not null check (day_index between 0 and 6),
  value int not null default 0 check (value in (0, 1)),
  week_start date not null,
  created_at timestamptz not null default now(),
  unique (habit_id, day_index, week_start)
);

create index idx_habit_logs_habit on public.habit_logs(habit_id, week_start);

-- 10. REFLECTIONS
create table public.reflections (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  week text not null,
  well text not null default '',
  improve text not null default '',
  win text not null default '',
  focus text not null default '',
  created_at timestamptz not null default now()
);

create index idx_reflections_user on public.reflections(user_id);

-- ROW LEVEL SECURITY
alter table public.profiles enable row level security;
alter table public.settings enable row level security;
alter table public.motivations enable row level security;
alter table public.tasks enable row level security;
alter table public.overdue_tasks enable row level security;
alter table public.goals enable row level security;
alter table public.goal_milestones enable row level security;
alter table public.habits enable row level security;
alter table public.habit_logs enable row level security;
alter table public.reflections enable row level security;

-- Users can only access their own data
create policy "Users can manage own profile"
  on public.profiles for all using (auth.uid() = id);

create policy "Users can manage own settings"
  on public.settings for all using (auth.uid() = user_id);

create policy "Users can manage own motivation"
  on public.motivations for all using (auth.uid() = user_id);

create policy "Users can manage own tasks"
  on public.tasks for all using (auth.uid() = user_id);

create policy "Users can manage own overdue tasks"
  on public.overdue_tasks for all using (auth.uid() = user_id);

create policy "Users can manage own goals"
  on public.goals for all using (auth.uid() = user_id);

create policy "Users can manage own goal milestones"
  on public.goal_milestones for all
  using (exists (select 1 from public.goals where goals.id = goal_milestones.goal_id and goals.user_id = auth.uid()));

create policy "Users can manage own habits"
  on public.habits for all using (auth.uid() = user_id);

create policy "Users can manage own habit logs"
  on public.habit_logs for all
  using (exists (select 1 from public.habits where habits.id = habit_logs.habit_id and habits.user_id = auth.uid()));

create policy "Users can manage own reflections"
  on public.reflections for all using (auth.uid() = user_id);

-- AUTO-CREATE PROFILE ON SIGNUP
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id) values (new.id);
  insert into public.settings (user_id) values (new.id);
  insert into public.motivations (user_id) values (new.id);
  return new;
end;
$$ language plpgsql security definer;

create or replace trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();
